version: "3.9"

services:
  backend:
    build: .
    network_mode: host
    environment:
      PORT: "8080"
      RESTART_INTERVAL_SECONDS: "86400"
      MONGO_URI: "${MONGO_URI:-mongodb://localhost:27017}"
      MARIADB_BASE_URI: "${MARIADB_BASE_URI:-groupmanager:xxxxx@tcp(127.0.0.1:3306)/}"
    restart: always
